START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2012
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2013
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2014
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2015
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2016
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2017
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2018
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2019
START C:\Users\arich\AppData\Local\mambaforge\envs\gis_py_8\python.exe C:/modeling/MirabelWohler/run_parallel.py June2020
